config/routes.rb
Fiveminuteruby::Application.routes.draw do |map|
  
  root :to => 'pages#index'
  
  resources :screencasts
  
  %w(about).each do |page|
    match page, :to => "pages##{page}", :as => page
  end
  

end

app/models/interested_user.rb
class InterestedUser < ActiveRecord::Base
  
end

app/models/screencast.rb
class Screencast < ActiveRecord::Base
  
  validates_presence_of %w(number url title)
  
  def to_param
    [id, title.downcase.gsub(/\s+/, '-').gsub(/[^\w-]/, '')].join('-')
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Fiveminuteruby::BasicAuth, Fiveminuteruby::EnsureWww
  
  protect_from_forgery
  
  layout 'application'
  
  scintillate
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  helper_method %w(screencasts)
  
  def index
    msg "Welcome to FiveMinuteRuy! This is a brand new site with lots of screencasts to come!"
  end
  
  private
  
  def screencasts
    @screencasts ||= Screencast.order('screencasts.number DESC')
  end
  
end

app/controllers/screencasts_controller.rb
class ScreencastsController < ApplicationController
  
  helper_method %w(screencast screencasts)
  
  # def index
  #   respond_to do |f|
  #     f.rss { render :xml => Screencast.order('screencasts.number DESC') }
  #   end 
  # end
  
  private
  
  def screencast
    @screencast ||= Screencast.find(params[:id])
  end
  
  def screencasts
    @screencasts ||= Screencast.order("screencasts.created_at DESC")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title
    "FiveMinuteRuby"
  end
  
  def feed_url
    if Rails.env.production?
      'http://feeds.feedburner.com/fiveminuteruby_screencasts'
    else
      screencasts_url(:format => :rss)
    end
  end
  
  def javascripts
    %w(
      http://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js
      application
    )
  end
  
  def stylesheets
    %w(application)
  end
  
  def meta_tags
    [
      {
        'content' => "text/html; charset=utf-8",
        'http-equiv' => "Content-type"
      },
      {
        'name' => "google-site-verification",
        'content' => "a_zoarsMpsPYWRu5z2hwh8iYDqeRuymVsAt1HolPxcw"
      }
    ].map { |attrs| HtmlMetaTag.new(attrs) }.join("\n").html_safe
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <%= meta_tags %>
    <title><%= title %></title>
    <%= stylesheet_link_tag stylesheets %>
    <%= javascript_include_tag javascripts %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="header">
        <h1><%= link_to image_tag("fiveminuteruby_logo.png"), root_path %></h1>
        <div class="clear"></div>
      </div>
      <div id="content">
        <div id="sidebar">
          <div class="sidebar_inner">
            <div id="menu">
              <ul>
                <li><%= link_to 'Screencasts', root_url %></li>
                <li class="rss_feed"><%= link_to 'RSS Feed', feed_url %></li>
                <li><%= link_to 'About this site', about_path %></li>
                <li><%= link_to 'Follow FiveMinuteRuby on Twitter', "http://twitter.com/fiveminuteruby" %></li>
              </ul>
            </div>
            <%= render 'shared/skribit' %>
            <%= render 'shared/donate_button' %>
          </div>
        </div>
        <div id="main">
          <div class="main_inner">
            <div id="messages">
              <% if has_msgs? %>
                <ul class="messages">
                  <% msgs.each do |m| %>
                    <li class="<%= [m.tone, 'message'].compact.join(' ') %>"><%= m %></li>
                  <% end %>
                </ul>
              <% end %>
            </div>
            <%= yield %>
          </div>
        </div>
        <div class="clear"></div>
      </div>
      <div id="footer">
        <p>&copy; <%= Time.zone.now.year %> Austin Schneider. Some rights reserved.</p>
      </div>
    </div>
    <%= javascript_tag do %>
      <%= yield :js %>
      <% if Rails.env.production? %>
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-17199780-1']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
      <% end %>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About This Site</h2>

<p>I love screencasts. I believe it's one of the best ways to learn and get better at a language. In these videos, I use the Ruby language and occasionally the Rails framework. The intent is to stay focused on the fundamentals of programming with some tips and tricks sprinkled in. I keep the videos under five minutes to help cut out unnecessary talking, coding, etc. I hope you enjoy and benefit from them.</p>

<h3>License</h3>

<p><span xmlns:dc="http://purl.org/dc/elements/1.1/" href="http://purl.org/dc/dcmitype/MovingImage" property="dc:title" rel="dc:type">FiveMinuteRuby Screencasts</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.fiveminuteruby.com" property="cc:attributionName" rel="cc:attributionURL">Austin Schneider</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/">Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License</a>.</p>

<div><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://creativecommons.org/images/public/somerights20.png" /></a></div>

app/views/pages/index.html.erb
<h2>Screencasts</h2>

<div id="screencasts">
  <% screencasts.each do |s| %>
    <%= div_for s do %>
      <h3 class="title"><%= link_to "##{s.number} #{s.title}", screencast_path(s) %></h3>
      <div class="date"><%= time_ago_in_words(s.created_at) %> ago</div>
      <div class="description"><%= simple_format s.description %></div>
    <% end %>
  <% end %>
</div>

app/views/screencasts/show.html.erb
<%= div_for screencast do %>
  <h3 class="title">#<%= screencast.number %> <%= screencast.title %></h3>
  <div class="description"><%= simple_format screencast.description %></div>
  <h3><strong><%= link_to 'Watch Screencast', screencast.url %></strong></h3>
  <% if screencast.youtube_url %>
    <p><strong><%= link_to 'Watch Smaller Version', screencast.youtube_url %> (for iPod/iPhone)</strong></p>
  <% end %>
<% end %>

<div class="comments">
  <%= render 'shared/disqus' %>
</div>

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>

<%= javascript_tag do %>
  /**
    * var disqus_identifier; [Optional but recommended: Define a unique identifier (e.g. post id or slug) for this thread] 
    */
  var disqus_developer = <%= Rails.env.production? ? 0 : 1 %>;
  (function() {
    var dsq = document.createElement('script');
    dsq.type = 'text/javascript';
    dsq.async = true;
    dsq.src = 'http://fiveminuteruby.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
<% end %>

<% content_for :js do %>
  (function() {
  	var links = document.getElementsByTagName('a');
  	var query = '?';
  	for(var i = 0; i < links.length; i++) {
  	  if(links[i].href.indexOf('#disqus_thread') >= 0) {
  		  query += 'url' + i + '=' + encodeURIComponent(links[i].href) + '&';
  	  }
    }
    document.write('<script charset="utf-8" type="text/javascript" src="http://disqus.com/forums/fiveminuteruby/get_num_replies.js' + query + '"></' + 'script>');
  })();
<% end %>

app/views/shared/_donate_button.html.erb
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
  <input type="hidden" name="cmd" value="_s-xclick">
  <input type="hidden" name="hosted_button_id" value="EYHHN7RMWLQKE">
  <p><input type="image" src="https://www.paypal.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
  <img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1"></p>
</form>

app/views/shared/_skribit.html.erb
<div id="writeSkribitHere"></div>

<%= javascript_include_tag 'http://assets.skribit.com/javascripts/SkribitWidget.js?renderTo=writeSkribitHere&amp;blog=90ce5549bd2e38ec5a059d9be45823c0&amp;cnt=5' %>